<a href="https://colab.research.google.com/github/rhapis97/Practice_AI/blob/main/20210624_BayesianProbability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

from nltk.corpus import stopwords
import string
import nltk

In [10]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [7]:
df = pd.read_csv('spam.xls.csv')
df

Unnamed: 0  num label                    text  label_num
0           0    1  spam       your free lottery          1
1           1    2  spam  free lottery free you           1
2           2    3   ham        your free apple           0
3           3    4   ham     free to contact me           0
4           4    5   ham             I won award          0
5           5    6  spam      my lottery ticket           1

In [16]:
def process_text(text):

  # text에서 구두점(punctuation)을 제거
  nopunc = [char for char in text if char not in string.punctuation]    # 구두점이 없다면 nopunc 리스트에 담기
  nopunc = ''.join(nopunc)    # 문자열 하나로 합치기

  # text에서 불용어 제거
  cleaned_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]    # 불용어 지우기(불용어에 해당하지 않는 것만 남기기)

  return cleaned_words

In [9]:
df['text'].head()

0         your free lottery
1    free lottery free you 
2          your free apple 
3       free to contact me 
4               I won award
Name: text, dtype: object

In [17]:
df['text'].apply(process_text)

0          [free, lottery]
1    [free, lottery, free]
2            [free, apple]
3          [free, contact]
4                  [award]
5        [lottery, ticket]
Name: text, dtype: object

In [18]:
# 행렬변환

from sklearn.feature_extraction.text import CountVectorizer
msg_bow = CountVectorizer(analyzer = process_text).fit_transform(df['text'])

In [19]:
msg_bow

<6x6 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [24]:
# data split(train: 80%, test: 20%)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(msg_bow, df['label_num'], test_size = 0.2, random_state=0)

In [25]:
# 다항식 나이브베이즈 모델 훈련

from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [26]:
classifier.predict(X_test)

array([1, 1])

In [27]:
y_test.values

array([1, 0])

In [28]:
classifier.predict(X_train)

array([1, 0, 1, 0])

In [29]:
y_train.values

array([1, 0, 1, 0])

In [ ]:
# train은 잘 맞추는데 test는 잘 못 맞춤(데이터 너무 적음)

In [30]:
# 모델 정확도

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score

In [31]:
pred = classifier.predict(X_train)    # 모델에 관한 예측값 출력

In [32]:
print(classification_report(y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         2

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



In [33]:
# confusion matrix

confusion_matrix(y_train, pred)

array([[2, 0],
       [0, 2]])

In [35]:
accuracy_score(y_train, pred)

1.0

In [36]:
y_test.values

array([1, 0])

In [37]:
classifier.predict(X_test)

array([1, 1])

In [38]:
pred = classifier.predict(X_test)

In [39]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      1.00      0.67         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [40]:
confusion_matrix(y_test, pred)

array([[0, 1],
       [0, 1]])

In [41]:
accuracy_score(y_test, pred)

0.5